package constants

const APPLICATION_NAME = "Ungoogled Updater"
const APPLICATION_NAME_LOWERCASE = "ungoogled_launcher"
const BIN_DIRECTORY = "bin_directory"
const CHROME_APPLICATION_NAME = "chrome.exe"
const CHROME_COMMAND_LINE_OPTIONS string = "chrome_command_line_options"
const DEBUG = "debug"
const DEFAULT_COMMAND = "updateandrun"
const DOWNLOAD_DIRECTORY = "download_directory"
const EMPTY string = ""
const FATAL_NORMAL_CASE string = "Fatal"
const HELP_SHORT_DESCRIPTION = "Show help for command"
const INFO_NORMAL_CASE string = "Info"
const INSTALLED_VERSION string = "installed_release"
const PROFILE_DIRECTORY = "profile_directory"
const SPACE = " "
const ROOT_LONG_DESCRIPTION = "Ungoogled Updater is a simple tool used to update your Ungoogled Chromium instance."
const ROOT_SHORT_DESCRIPTION = "Simple program used to update your Ungoogled Chromium instance."
const VERSION_LONG_DESCRIPTION = "Show the version information."
const VERSION_SHORT_DESCRIPTION = "Show the version information"
const WEB_LONG_DESCRIPTION = "Open the Ungoogled Updater website in your default browser."
const WEB_SHORT_DESCRIPTION = "Open the Ungoogled Updater website in your default browser"
const WEB_SITE string = "https://github.com/jlanzarotta/ungoogled_launcher/"
