image:https://img.shields.io/github/v/release/jlanzarotta/ungoogled_launcher[GitHub Release]
image:https://img.shields.io/github/downloads/jlanzarotta/ungoogled_launcher/total[GitHub Downloads (all assets, all releases)]
image:https://img.shields.io/github/go-mod/go-version/jlanzarotta/ungoogled_launcher[Go Version]

= Ungoogled Launcher
:toc: preamble
:toclevels: 7
:icons: font
:sectnums:
:numbered:
:table-stripes: even

Ungoogled Launcher is a simple command line tool use to update and run an instance of Ungoogled Chromium.

== Installation

You can install Ungoogled Launcher using [scoop](https://scoop.sh/). It is in the `ungoogled_launcher` bucket:

[source, shell]
----
# Add my scoops.
> scoop bucket add jlanzarotta https://github.com/jlanzarotta/scoops

# Install Ungoogled Launcher.
> scoop install jlanzarotta/ungoogled_launcher
----

=== Other operating systems

To install Ungoogled Launcher, simply unzip the archive for your specific
operating system into the directory of your choice.

== Configuration

When Ungoogled Launcher starts up, it checks to make sure there is a default
configuration file.  If it does not exist, it is automatically created for you.

NOTE: Ungoogled Launcher support the use of the _XDG Base Directory
Specification_. For more information https://specifications.freedesktop.org/basedir-spec/latest/

Ungoogled Launcher uses the following precedence order when determining where
the configuration file is located. Each item listed, takes precedence over the
item below it:

[cols="1,1a"]
|===
|Microsoft Windows(R)
|. %XDG_CONFIG_HOME%/ungoogled_launcher/.ungoogled_launcher.yaml
. %USERPROFILE%/.ungoogled_launcher.yaml
|===

=== Default Configuration

The default Microsoft Windows(R) Ungoogled Launcher configuration is as follows.  These
configuration options can be modified by the user after installation.

[source, yaml]
----
bin_directory: bin <1>
chrome_command_line_options: --no-default-browser-check <2>
debug: false <3>
download_directory: download <4>
installed_release: "" <5>
pause_after_run: false <6>
----

<1> The directory there Ungoogled Launcher will install the Ungoogled Chromium runtime files.
<2> Any additional command-line options used when running Chromium.
<3> If debug information should be shown or not, and written to debug file.
<4> The directory where Ungoogled Launcher downloads the latest release of Ungoogled Chromium.
<5> The version number of the installed version of Ungoogled Chromium.
<6> If Ungoogled Launcher should pause after a successful run.

=== Default Browser

Ungoogled Launcher has feature to use portable Chromium as default browser and
it will be open links from another programs through Ungoogled Launcher.

- start "SetDefaultBrowser.bat" (as admin).
- start "Control panel" -> "Default programs" -> "Set your default programs" -> "Ungoogled Launcher" and set all checkboxes on.

== Copyright and License

BSD 3-Clause License

Copyright (c) 2018-{localyear}, Jeff Lanzarotta
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,this list of conditions, and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
